spring.application.name=microservice-eureka
server.port=8761

# No registrar ni buscar otros servicios
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Configuración de instancia
# Usa el dominio público de Render o nombre interno
eureka.instance.hostname=eureka-server
eureka.instance.non-secure-port-enabled=true
eureka.instance.secure-port-enabled=false
