spring.application.name=microservice-eureka
server.port=8761

# Eureka Server no se registra a sí mismo
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Configuración de URL del servicio
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Configuración para Render
eureka.instance.hostname=${EUREKA_HOSTNAME:localhost}
eureka.instance.prefer-ip-address=false

# Desactivar health checks de Eureka
management.health.eureka.enabled=false