
spring.application.name=microservice-gateway
server.port=8080
spring.main.web-application-type=reactive

# URL del Eureka Server (usa el nombre del servicio en docker-compose)
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/

# Registrar el gateway en Eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Preferir IP o hostname del contenedor
eureka.instance.prefer-ip-address=true
eureka.instance.hostname=microservice-gateway

# (Permite crear rutas automáticamente desde Eureka)
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true


spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-origins=http://localhost:3000
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-methods=GET,POST,PUT,PATCH,DELETE,OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-headers=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allow-credentials=true


spring.web.resources.add-mappings=false
