spring.application.name=microservice-gateway
server.port=8080

spring.main.web-application-type=reactive
spring.web.resources.add-mappings=false

# --- Eureka client ---
eureka.client.service-url.defaultZone=https://fluxora-e3su.onrender.com/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true
eureka.client.tls.skip-ssl-validation=true
# Para Render: expón tu URL pública si quieres verla reflejada en Eureka
eureka.instance.hostname=fluxora-i000.onrender.com

# --- Gateway rutas (sin tocar tus URIs locales por ahora) ---
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

eureka.instance.non-secure-port-enabled=false
eureka.instance.secure-port-enabled=true

# CORS ahora está configurado en CorsConfig.java
