spring.config.import=optional:file:.env[.properties]

spring.application.name=microservice-inventario
server.port=${SERVER_PORT:8082}
server.servlet.context-path=/api/inventario

# --- Base de datos ---
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# --- JPA / Hibernate ---
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# --- Optimización Hikari (para Render) ---
spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=20000
spring.datasource.hikari.connection-timeout=20000

# --- Eureka ---
eureka.client.service-url.defaultZone=${EUREKA_URL}
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.instance.prefer-ip-address=true
eureka.instance.hostname=${RENDER_EXTERNAL_URL:microservice-inventario}

# --- JWT ---
security.jwt.secret=${JWT_SECRET}
security.jwt.expiration-minutes=${JWT_EXP}
