spring.config.import=optional:file:.env[.properties]

spring.application.name=microservice-cliente
server.port=${SERVER_PORT:8083}
server.servlet.context-path=/api/clientes

# =============================
# 🔹 CONFIGURACIÓN BASE DE DATOS
# =============================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Evitar fallo si la conexión inicial a Supabase tarda o se corta
spring.datasource.hikari.initializationFailTimeout=0
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.maximum-pool-size=3

# =============================
# 🔹 JPA / HIBERNATE
# =============================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

# =============================
# 🔹 EUREKA CLIENT
# =============================
eureka.client.service-url.defaultZone=${EUREKA_URL}
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.instance.prefer-ip-address=true
eureka.instance.hostname=${RENDER_EXTERNAL_URL:microservice-cliente}

# Ignorar validaciones SSL y habilitar puertos seguros como en Gateway
eureka.client.tls.skip-ssl-validation=true
eureka.instance.non-secure-port-enabled=false
eureka.instance.secure-port-enabled=true

# =============================
# 🔹 JWT
# =============================
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXP}
